name: Update Version and Tag

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: 'Version type to increment (patch, minor, or major). Do not use with specific_version.'
        required: false
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major
      specific_version:
        description: 'Specific version to set (e.g., 1.2.3). Overrides version_type.'
        required: false

jobs:
  update_version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v5.0.0
        with:
          # We need to fetch all history and tags
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v6.0.0
        with:
          node-version: 22

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Update version and create tag
        id: version
        run: |
          if [ -n "${{ github.event.inputs.specific_version }}" ]; then
            npm version ${{ github.event.inputs.specific_version }} -m "chore: bump version to %s"
          else
            npm version ${{ github.event.inputs.version_type }} -m "chore: bump version to %s"
          fi
      
      - name: Push changes
        run: |
          git push --follow-tags
      
      - name: Trigger release workflow
        run: gh workflow run release.yml --ref $(git rev-parse --abbrev-ref HEAD)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}